version: "2"

services:
  registry:
    build: registry
    container_name: "registry-srv"
    volumes:
    - "${REGISTRY_HOME}:/var/lib/registry/"
    - "${HTPASSWD_HOME}:/auth/"
    expose:
    - 5000
    environment:
    - REGISTRY_AUTH=htpasswd
    - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
    - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
    - REGISTRY_STORAGE_DELETE_ENABLED=true
    restart: "unless-stopped"

  nginx:
    build: ./nginx
    container_name: "registry-nginx"
    ports:
    - "5043:443"
    - "5044:444"
    volumes:
    - ${REGISTRY_SSL_CERT_PATH}:/etc/nginx/ssl
    depends_on:
    - registry
    restart: "unless-stopped"