version: "2"

services:
  registry:
    build: registry
    container_name: "registry-srv"
    volumes:
      - "${REGISTRY_HOME}:/var/lib/registry/"
    ports:
      - "127.0.0.1:5000:5000"
    restart: "unless-stopped"