version: "2"

services:
  registry:
    image: registry:2
    container_name: "registry-srv"
    volumes:
      - "./registry:/var/lib/registry/"
      - "./auth/:/auth/"
      - "./config.yml:/etc/docker/registry/config.yml"
    expose:
      - 5000
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    restart: "unless-stopped"

  nginx:
    build: ./nginx
    container_name: "registry-nginx"
    links:
      - registry
    ports:
      - "5043:443"
      - "5044:444"
    volumes:
      - ./nginx/tls:/etc/nginx/ssl
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - registry
    external_links:
      - registry-web:manager
    restart: "unless-stopped"