version: "2"

services:
  registry:
    build: registry
    container_name: "registry-srv"
    volumes:
      - "${REGISTRY_HOME}:/var/lib/registry/"
      - "${HTPASSWD_HOME}:/auth/"
      - "./letsencrypt/cachefile:/letsencrypt/cachefile"
    ports:
      - "443:5000"

    restart: "unless-stopped"
    environment:
      - REGISTRY_HTTP_TLS_LETSENCRYPT_CACHEFILE=/letsencrypt/cachefile
      - REGISTRY_HTTP_TLS_LETSENCRYPT_EMAIL=test@emawind.com
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
    restart: "unless-stopped"