version: "2"

services:
  registry:
    image: registry:2
    container_name: "registry-srv"
    volumes:
      - "./registry:/var/lib/registry/"
    ports:
      - "127.0.0.1:5000:5000"
    restart: "unless-stopped"